services:
  nuxt:
    build: 
      context: .
      dockerfile: docker/nuxt/Dockerfile
    container_name: nuxt
    env_file:
      - .env
    volumes:
      - ./front:/app:cached 
      - nuxt_node_modules:/app/node_modules 
    ports: 
      - "80:3000"
      - "24678:24678"
    tty: true 
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      CHOKIDAR_USEPOLLING: true
      NUXT_UPLOADTHING_TOKEN: ${NUXT_UPLOADTHING_TOKEN}
    command: sh -c "npm install && npm run dev"

  fast_api:
    build:
      context: .
      dockerfile: docker/fastAPI/Dockerfile 
    container_name: fast_api
    env_file:
      - ./backend/.env
    ports:
        - "8000:8000"
    volumes: 
        - ./backend/app:/app:cached
    depends_on:
      db:
        condition: service_healthy        

  db:
    image: mysql:8.0
    container_name: db 
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sample_db
      MYSQL_USER: mysqluser 
      MYSQL_PASSWORD: mysqlpass 
    volumes:
      - ./db/data:/var/lib/mysql 
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/initdb.d:/docker-entrypoint-initdb.d 
    ports:
      - 3308:3306 
    command: --port 3306 
    tty: true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-prootpass"]
      interval: 3s
      timeout: 2s
      retries: 20
      start_period: 15s

  adminer:
    image: adminer 
    container_name: adminer 
    ports:
      - 8001:8080
    depends_on:
      - db
        
volumes:
  nuxt_node_modules:
